# Llave unica para tu proyecto en SonarQube
sonar.projectKey=farmacia_local

# Nombre del proyecto
sonar.projectName=Proyecto Farmacia

# Directorio a analizar (el punto significa la carpeta actual)
sonar.sources=.

# URL del servidor local
sonar.host.url=http://localhost:9000

# Tu token generado en SonarQube
sonar.token=squ_f3a963f3f2da32dd07893da58d81ff2b17ebb1ac

# Ruta de Node.js (necesaria si tu proyecto tiene algo de JavaScript, TypeScript o CSS)
sonar.nodejs.executable=/usr/bin/node
